# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0002_entity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded', models.ManyToManyField(related_name='identity_excluded_set', to='uploads.Entity')),
                ('identity', models.ManyToManyField(related_name='identity_source_set', to='uploads.Entity')),
                ('matchs', models.ManyToManyField(related_name='identity_matchs_set', to='uploads.Entity')),
            ],
        ),
    ]
