# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='identity',
            name='excluded',
            field=models.ManyToManyField(blank=True, related_name='identity_excluded_set', to='uploads.Entity'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity',
            field=models.ManyToManyField(blank=True, related_name='identity_source_set', to='uploads.Entity'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='matchs',
            field=models.ManyToManyField(blank=True, related_name='identity_matchs_set', to='uploads.Entity'),
        ),
    ]
