# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20170906_1912'),
        ('identity', '0002_auto_20180911_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_matchs_set', to='uploads.Entity')),
            ],
        ),
        migrations.RemoveField(
            model_name='identity',
            name='matchs',
        ),
        migrations.AddField(
            model_name='identitymatch',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='identity.Identity'),
        ),
    ]
