# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-12 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20170906_1912'),
        ('identity', '0003_auto_20180912_1630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identitymatch',
            unique_together=set([('entity', 'identity')]),
        ),
    ]
