# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20180912_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitymatch',
            name='euclidean_distance',
            field=models.FloatField(default=0),
        ),
    ]
