# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_common.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0)),
                ('top', models.PositiveIntegerField(default=0)),
                ('right', models.PositiveIntegerField(default=0)),
                ('bottom', models.PositiveIntegerField(default=0)),
                ('left', models.PositiveIntegerField(default=0)),
                ('meta', django_common.db_fields.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='uploads/%Y-%m-%d/')),
                ('darknet_processing_start', models.DateTimeField(blank=True, null=True)),
                ('darknet_processing_end', models.DateTimeField(blank=True, null=True)),
                ('dlib_processing_start', models.DateTimeField(blank=True, null=True)),
                ('dlib_processing_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.Upload'),
        ),
    ]
