# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/%Y-%m-%d/'),
        ),
    ]
